#!/usr/bin/env bash
# Print the Homebrew cask for one release of COAT (or COAT Preview).
#
#   write-cask.sh <stable|preview> <version> <sha256 of the macOS zip> <owner/repo>
#
# The release workflow runs this and commits the result to the Homebrew tap
# (Casks/coat.rb, or Casks/coat@preview.rb), so `brew install --cask <owner>/tap/coat` always
# gets the newest release. See docs/releasing.md.
set -euo pipefail
channel=${1:?channel}; version=${2:?version}; sha256=${3:?sha256}; repo=${4:?owner/repo}

if [ "$channel" = preview ]; then
  token="coat@preview" name="COAT Preview" app="COAT Preview.app" file="COAT_v#{version}_PREVIEW.zip"
  desc="Preview build of COAT: trace a phone call through simlog"
  settings="COAT Preview" bundle=se.telavox.coat.preview
else
  token="coat" name="COAT" app="COAT.app" file="COAT_v#{version}.zip"
  desc="Trace a phone call through simlog: its route, why each hop happened, problems"
  settings="COAT" bundle=se.telavox.coat
fi

cat <<CASK
# Generated by packaging/homebrew/write-cask.sh in ${repo}; don't edit by hand.
cask "${token}" do
  version "${version}"
  sha256 "${sha256}"

  url "https://github.com/${repo}/releases/download/v#{version}/${file}"
  name "${name}"
  desc "${desc}"
  homepage "https://github.com/${repo}"

  # COAT updates itself, so \`brew upgrade\` leaves it alone unless you add --greedy.
  auto_updates true
  depends_on :macos

  app "${app}"

  zap trash: [
    "~/Library/Application Support/${settings}",
    "~/Library/Preferences/${bundle}.plist",
  ]
end
CASK
